ZSH=${HOME}/.zsh
ZSH_CACHE_DIR=${ZSH}/cache/
fpath=($ZSH/functions $fpath)
ppath=($ZSH/plugins)
autoload -U colors zsh/terminfo && colors
autoload -U promptinit && promptinit
autoload -U compinit && compinit    #Initilize && load completion system

source ${ZSH}/config_files/path.zsh
source ${ZSH}/config_files/local.zsh
source ${ZSH}/config_files/aliases.zsh
source ${ZSH}/config_files/colors.zsh
source ${ZSH}/config_files/completion.zsh
source ${ZSH}/config_files/enviroment.zsh
source ${ZSH}/config_files/git.zsh
source ${ZSH}/config_files/history.zsh
source ${ZSH}/config_files/key-bindings.zsh
source ${ZSH}/config_files/prompt.zsh
source ${ZSH}/config_files/setopt.zsh
source ${ZSH}/config_files/spectrum.zsh

# source ${ZSH}/base16-shell/scripts/base16-atelier-sulphurpool.sh
source ${ZSH}/base16-shell/scripts/base16-material.sh

#
# PLUGINS
#
source ${ZSH}/themes/gitster.zsh-theme
source $ppath/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ppath/z/z.sh
source $ppath/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source $ppath/zsh-vimode-visual/zsh-vimode-visual.zsh

# Swap ctrl and caps if setxkbmap exists
if (( $+commands[setxkbmap] )); then
setxkbmap -option ctrl:swapcaps
fi

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

if [[ $(tty) = /dev/tty1 ]]; then
  exec startx
fi

#ENABLE_CORRECTION="true"
#
export TERM='xterm-256color'
